# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csyncer.proto\x12\x16kwilson272.file_syncer\"\x15\n\x07\x46ileKey\x12\n\n\x02id\x18\x01 \x01(\t\"\x82\x01\n\x08\x46ileDesc\x12\x30\n\x05state\x18\x01 \x01(\x0e\x32!.kwilson272.file_syncer.FileState\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x1e\n\x16last_modification_time\x18\x03 \x01(\x01\x12\x11\n\tfile_size\x18\x04 \x01(\x05\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c*e\n\tFileState\x12\x14\n\x10UNKNOWN_FILE_KEY\x10\x00\x12\x14\n\x10\x46ILE_NOT_PRESENT\x10\x01\x12\x15\n\x11\x46ILE_NOT_READABLE\x10\x02\x12\x15\n\x11\x44OWNLOAD_POSSIBLE\x10\x03\x32\xb2\x01\n\nFileServer\x12R\n\rreq_file_desc\x12\x1f.kwilson272.file_syncer.FileKey\x1a .kwilson272.file_syncer.FileDesc\x12P\n\x08\x64ownload\x12\x1f.kwilson272.file_syncer.FileKey\x1a!.kwilson272.file_syncer.FileChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'syncer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILESTATE']._serialized_start=226
  _globals['_FILESTATE']._serialized_end=327
  _globals['_FILEKEY']._serialized_start=40
  _globals['_FILEKEY']._serialized_end=61
  _globals['_FILEDESC']._serialized_start=64
  _globals['_FILEDESC']._serialized_end=194
  _globals['_FILECHUNK']._serialized_start=196
  _globals['_FILECHUNK']._serialized_end=224
  _globals['_FILESERVER']._serialized_start=330
  _globals['_FILESERVER']._serialized_end=508
# @@protoc_insertion_point(module_scope)
